### PR TITLE
Add react-split types definition

### PR DESCRIPTION
**Pull request by fabien0102**
### Related issue
#283 

Just adding the types for react-split (copy-past from split-js + some adjustement to fit the react implementation)

I would love to try the package locally, but I totally forgot how to use lerna to build the package 🙄 But normally, everything should follow, I hope

### CODE REVIEW

**Comment by nathancahill** [comment]
Thanks! Looks great. I'm wondering if we can import more of the types from `split.js` like you did with `CSSStyleDeclarationPartial` to avoid duplicating types?

**Comment by dlcognite** [comment]
is there any blockers to merging this :O

**Comment by peroo** [comment]
The definitions seem to be missing the the arguments to `onDragEnd`, etc. Since I only use that function I resolved it by omitting `onDragEnd` from the `HTMLDivElement` extend, and changing the `onDragEnd` signature to `onDragEnd?(sizes: number[]): void`.

**Comment by fgblomqvist** [comment]
Any chance at getting this merged @lijunle? If there is more work to be done, let us know and I'm sure we can help 🙂

**Comment by laubonghaudoi** [comment]
Why isn't this merged yet?

**Comment by fabien0102** [comment]
This was apparently fixed on `master`

https://github.com/nathancahill/split/commit/c2f2ac2f0c9037d4a1efdfe7e6d40e60845d209a#diff-912fb417748d184f68f4ab13158b3c90bd1dd9eab94610a67f5d7ead09e73279

**Pull request closed without merging**
