### PR TITLE
WIP – Issues/85 drag push other panes

### PR DESCRIPTION
**Pull request by long-lazuli**
Hello !
This is answering to issue #85 .

It has to be reviewed, as there is probably some some bugs :
- When you go really quick, you may push next pane without closing the actual one.
- Does not push multiple panes.

### CODE REVIEW

**Comment by oskarkrawczyk** [comment]
@long-lazuli This looks really great!

One thing I've noticed (Safari 11.0.3) is this:

kapture 2018-03-16 at 17 51 02

Without moving the left handle, the right one will not push the left. But as soon as you do move the left one, the right will start working as expected.

You're really close here! 👍

**Comment by long-lazuli** [comment]
Yes, I just saw this bug, and also a freeze right now, as I was updating docs.
I will take some hours to finish this until tomorrow.

**Comment by long-lazuli** [comment]
The freezing bug is resolved.

But I'm not fully satisfied by code, I probably calculate dimensions too many times.  
I never had a visible performance issue, but it could certainly be better.

There is also still the problem of speed-dragging, where the middle element is not shrinking to min-size. I would also like to be able to push many elements.

So there is still some works.

Also, gzip size is currently 1.98 kB. It is not 2kB, but it's close.  
I think it's possible to shrink it a little bit.

**Comment by long-lazuli** [comment]
Almost finish.
Two more things to do :
- [ ] fix puhed-pane 's min width
- [ ] retrieve original gutters positions when drag back to a "non-pushing state"

**Pull request closed without merging**
